import TinyMLP.Defs.SpecCore
import TinyMLP.Interfaces.ArithmeticProofProvider
import TinyMLP.ProofsVanilla.SpecArithmetic
import TinyMLP.Defs.FixedPointCore
import TinyMLP.ProofsVanilla.FixedPoint
import TinyMLP.Defs.MachineCore
import TinyMLP.Defs.TemporalCore
import TinyMLP.Defs.CorrectnessGoals
import TinyMLP.ProofsVanilla.Invariants
import TinyMLP.ProofsVanilla.Simulation
import TinyMLP.ProofsVanilla.Temporal
import TinyMLP.ProofsVanilla.Correctness
