from __future__ import annotations

import json
import subprocess
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "rtl-formalize-synthesis" / "scripts" / "generate_wrapper.py"
VALID_RAW_MODULE = """\
// Generated by Sparkle HDL
// Module: TinyMLP.sparkleMlpCorePacked

module TinyMLP_sparkleMlpCorePacked (
  input logic _gen_start,
  input logic [7:0] _gen_in0,
  input logic [7:0] _gen_in1,
  input logic [7:0] _gen_in2,
  input logic [7:0] _gen_in3,
  input logic clk,
  input logic rst,
  output logic [298:0] out
);
  assign out = 299'd0;
endmodule
"""


def run_generator(*args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["python3", str(SCRIPT), *args],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )


def write_subset_manifest(path: Path, *, raw_module_name: str = "TinyMLP_sparkleMlpCorePacked") -> None:
    payload = {
        "schema_version": 1,
        "declared_emitted_subset": {
            "entrypoint": "TinyMLPSparkle.Emit",
            "raw_artifact": "rtl-formalize-synthesis/results/canonical/sv/sparkle_mlp_core.sv",
            "emit_source_paths": [
                "rtl-formalize-synthesis/src/TinyMLPSparkle/Emit.lean",
                "rtl-formalize-synthesis/src/TinyMLPSparkle/MlpCoreSignal.lean",
            ],
            "raw_module_name": raw_module_name,
            "required_header_comments": [
                "// Generated by Sparkle HDL",
                "// Module: TinyMLP.sparkleMlpCorePacked",
            ],
            "expected_raw_ports": [
                {"direction": "input", "name": "_gen_start", "width": 1},
                {"direction": "input", "name": "_gen_in0", "width": 8},
                {"direction": "input", "name": "_gen_in1", "width": 8},
                {"direction": "input", "name": "_gen_in2", "width": 8},
                {"direction": "input", "name": "_gen_in3", "width": 8},
                {"direction": "input", "name": "clk", "width": 1},
                {"direction": "input", "name": "rst", "width": 1},
                {"direction": "output", "name": "out", "width": 299},
            ],
        },
        "semantics_preservation_statement": {
            "source_model": "Sparkle Signal DSL full-core model emitted by TinyMLPSparkle.Emit",
            "target_artifact": "rtl-formalize-synthesis/results/canonical/sv/sparkle_mlp_core.sv::TinyMLP_sparkleMlpCorePacked",
            "verification_scope": "Declared emitted subset only",
            "residual_validation_surfaces": [
                "wrapper reconstruction",
                "downstream validation",
            ],
        },
    }
    path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")


class GenerateWrapperTests(unittest.TestCase):
    def test_rejects_raw_module_missing_expected_ports(self) -> None:
        with tempfile.TemporaryDirectory(dir=ROOT / "build") as tmpdir:
            raw_path = Path(tmpdir) / "sparkle_mlp_core.sv"
            wrapper_path = Path(tmpdir) / "sparkle_mlp_core_wrapper.sv"
            raw_path.write_text(
                "module TinyMLP_sparkleMlpCorePacked (\n"
                "  input logic clk,\n"
                "  output logic [298:0] out\n"
                ");\n"
                "  assign out = 299'd0;\n"
                "endmodule\n",
                encoding="utf-8",
            )

            result = run_generator("--raw", str(raw_path), "--wrapper", str(wrapper_path))

            self.assertNotEqual(result.returncode, 0, msg=result.stdout + result.stderr)
            self.assertIn("raw module interface validation failed", result.stderr)
            self.assertIn("missing ports", result.stderr)

    def test_check_mode_rejects_wrapper_mismatch(self) -> None:
        with tempfile.TemporaryDirectory(dir=ROOT / "build") as tmpdir:
            raw_path = Path(tmpdir) / "sparkle_mlp_core.sv"
            wrapper_path = Path(tmpdir) / "sparkle_mlp_core_wrapper.sv"
            raw_path.write_text(VALID_RAW_MODULE, encoding="utf-8")

            generate = run_generator("--raw", str(raw_path), "--wrapper", str(wrapper_path))
            self.assertEqual(generate.returncode, 0, msg=generate.stdout + generate.stderr)

            wrapper_path.write_text("module mlp_core; endmodule\n", encoding="utf-8")
            check = run_generator("--raw", str(raw_path), "--wrapper", str(wrapper_path), "--check")

            self.assertNotEqual(check.returncode, 0, msg=check.stdout + check.stderr)
            self.assertIn("wrapper check failed", check.stderr)

    def test_subset_manifest_rejects_raw_module_outside_declared_subset(self) -> None:
        with tempfile.TemporaryDirectory(dir=ROOT / "build") as tmpdir:
            raw_path = Path(tmpdir) / "sparkle_mlp_core.sv"
            wrapper_path = Path(tmpdir) / "sparkle_mlp_core_wrapper.sv"
            manifest_path = Path(tmpdir) / "verification_manifest.json"
            raw_path.write_text(VALID_RAW_MODULE, encoding="utf-8")
            write_subset_manifest(manifest_path, raw_module_name="UnexpectedPackedModule")

            result = run_generator(
                "--raw",
                str(raw_path),
                "--wrapper",
                str(wrapper_path),
                "--subset-manifest",
                str(manifest_path),
            )

            self.assertNotEqual(result.returncode, 0, msg=result.stdout + result.stderr)
            self.assertIn("emitted subset validation failed", result.stderr)


if __name__ == "__main__":
    unittest.main()
