from __future__ import annotations

import json
from itertools import product
from pathlib import Path
from typing import Iterable, Sequence

from .artifacts import CONTRACT_WEIGHTS_PATH, ROOT
from .params import HIDDEN_SIZE, INPUT_SIZE
from .quantize_helpers import relu, wrap_signed
from .schema import coerce_weights_payload

TEST_VECTORS_PATH = ROOT / "simulations" / "rtl" / "test_vectors.mem"
TEST_VECTORS_META_PATH = ROOT / "simulations" / "rtl" / "test_vectors_meta.svh"
VECTOR_HEX_WIDTH = 17

SMOKE_VECTORS = (
    (-8, -3, 2, 1),
    (7, -2, 3, -1),
    (12, 6, -5, -2),
    (-4, 9, -3, 7),
    (0, 0, 0, 0),
    (15, -16, 12, -8),
    (-32, 31, -7, 9),
    (63, -12, 5, -1),
    (-11, -9, 14, 8),
    (20, 2, -18, 3),
    (-64, 5, 33, -17),
    (19, -21, 11, 4),
    (-7, 4, -12, 13),
)
WITNESS_VALUES = (-32, -16, -8, -4, -2, -1, 0, 1, 2, 4, 8, 16, 32)
WITNESS_CLASSES = ("positive", "zero", "negative")


def _normalize_input(values: Iterable[int]) -> tuple[int, int, int, int]:
    data = tuple(wrap_signed(v, 8) for v in values)
    if len(data) != INPUT_SIZE:
        raise ValueError(f"expected {INPUT_SIZE} inputs, got {len(data)}")
    return data  # type: ignore[return-value]


def _score(values: Sequence[int], weights: dict[str, object]) -> int:
    xs = _normalize_input(values)
    w1 = weights["w1"]
    b1 = weights["b1"]
    hidden: list[int] = []
    for i in range(HIDDEN_SIZE):
        acc = 0
        for j in range(INPUT_SIZE):
            product = wrap_signed(xs[j] * w1[i][j], 16)
            acc = wrap_signed(acc + product, 32)
        acc = wrap_signed(acc + b1[i], 32)
        hidden.append(wrap_signed(relu(acc), 16))

    w2 = weights["w2"]
    b2 = weights["b2"]
    acc = 0
    for i in range(HIDDEN_SIZE):
        product = wrap_signed(hidden[i] * w2[i], 24)
        acc = wrap_signed(acc + product, 32)
    return wrap_signed(acc + b2, 32)


def _pack_vector(values: Sequence[int], score: int) -> int:
    xs = _normalize_input(values)
    expected = int(score > 0)
    word = wrap_signed(score, 32) & 0xFFFFFFFF
    word = (word << 1) | (expected & 0x1)
    for value in xs:
        word = (word << 8) | (value & 0xFF)
    return word


def _score_class(score: int) -> str:
    if score > 0:
        return "positive"
    if score == 0:
        return "zero"
    return "negative"


def _build_vectors(weights: dict[str, object]) -> tuple[tuple[int, int, int, int], ...]:
    selected = list(SMOKE_VECTORS)
    used = set(selected)

    for target_class in WITNESS_CLASSES:
        witness: tuple[int, int, int, int] | None = None
        for candidate in product(WITNESS_VALUES, repeat=INPUT_SIZE):
            vector = tuple(candidate)
            if vector in used:
                continue
            if _score_class(_score(vector, weights=weights)) == target_class:
                witness = vector
                break
        if witness is None:
            raise ValueError(
                "unable to synthesize required score-class witnesses "
                f"for {target_class} from the deterministic candidate pool"
            )
        selected.append(witness)
        used.add(witness)

    return tuple(selected)


def _load_contract_weights() -> dict[str, object]:
    if not CONTRACT_WEIGHTS_PATH.exists():
        raise FileNotFoundError(f"missing contract weights file: {CONTRACT_WEIGHTS_PATH}")
    return coerce_weights_payload(
        json.loads(CONTRACT_WEIGHTS_PATH.read_text(encoding="utf-8")),
        label="contract weights",
    )


def _build_scored_vectors(weights: dict[str, object]) -> tuple[tuple[tuple[int, int, int, int], int], ...]:
    return tuple((vector, _score(vector, weights=weights)) for vector in _build_vectors(weights))


def render_vectors(weights: dict[str, object]) -> str:
    lines = []
    for vector, score in _build_scored_vectors(weights):
        lines.append(f"{_pack_vector(vector, score):0{VECTOR_HEX_WIDTH}x}")
    return "\n".join(lines) + "\n"


def render_vector_meta(weights: dict[str, object]) -> str:
    vector_count = len(_build_scored_vectors(weights))
    return (
        "// Generated by contract.src.gen_vectors. Do not edit.\n"
        f"localparam int NUM_VECTORS = {vector_count};\n"
    )


def expected_vector_artifacts(weights: dict[str, object]) -> dict[Path, str]:
    return {
        TEST_VECTORS_PATH: render_vectors(weights),
        TEST_VECTORS_META_PATH: render_vector_meta(weights),
    }


def generate_vectors() -> Path:
    weights = _load_contract_weights()
    for out_path, text in expected_vector_artifacts(weights).items():
        out_path.write_text(text, encoding="ascii")
    return TEST_VECTORS_PATH


def main() -> None:
    out_path = generate_vectors()
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
